#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import logging
from pathlib import Path
import shutil
import subprocess
from typing import Tuple, Union
import os
import numpy as np
# Headless backend so this works inside Docker with no GUI
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib import colors as mcolors

from surfmap import PATH_MSMS, __COPYRIGHT_FULL__
from surfmap.lib.logs import get_logger
from surfmap.lib.parameters import Parameters
from surfmap.lib.utils import JunkFilePath
from surfmap.tools.SurfmapTools import run_particles_mapping
from surfmap.tools.compute_shell import run as run_compute_shell
from surfmap.tools.compute_electrostatics import run as run_compute_electrostatics


logger = get_logger(name=__name__)


def compute_coords_list(params: Parameters, coords_file: str, property: str) -> Tuple[int, str]:
    """Compute phi theta list

    Args:
        params (Parameters): Object with a set of useful parameters:
            - params.coords_script  # path to the script computeCoordsList.r
            - params.pdbarg  # pdb filename
            - params.outdir  # path to the output directory
            - params.cellsize  # unit size of a grid cell
            - params.proj  # name of the projection type
        coords_file (str): # path to filename with spherical coordinates of each residue
        property (str): property to map

    Returns:
        tuple[int, str]: return the status value of the process and the output filename
    """
    cmd = ["Rscript", params.coords_script, "-f", str(coords_file), "-s", str(params.cellsize), "-P", params.proj, "-o", params.outdir]
    
    logger.debug(f"Running the command: {' '.join(cmd)}")
    proc_status = subprocess.call(cmd)
    
    if proc_status != 0:
        logger.error(f"Error occured during the computation of spherical coordinates of particles, the process will stop.")
        exit(1)

    # output file generated by params.coords_script
    out_file = str(Path(params.outdir) / "coord_lists" / f"{Path(params.pdbarg).stem}_{property}_coord_list.txt")

    return proc_status, out_file


def compute_matrix(params: Parameters, coords_file: str, property: str, suffix="_coord_list.txt") -> Tuple[int, str, str]:
    """Compute matrix files

    Args:
        params (Parameters): Object with a set of useful parameters:
            - params.matrix_script  # path to the script computeMatrices.r
            - params.pdbarg  # pdb filename
            - params.outdir  # path to the output directory
            - params.cellsize  # unit size of a grid cell
            - params.proj  # name of the projection type
        coords_file (str): # path to filename with coords_list (output of compute_coords_list())
        property (str): property to map

    Returns:
        tuple[int, str, str]: return the status value of the process, the output filenames of the matrix file and the smoothed matrix file.
    """

    # generic command for binding sites property
    cmd = ["Rscript", params.matrix_script, "-i", coords_file, "-s", str(params.cellsize), "-P", str(params.proj), "-o", str(params.outdir), "--suffix", suffix, "--discrete"]

    # adapt command according to property
    if property != "binding_sites":
        if not params.nosmooth:
            del cmd[-1]
        else:
            cmd[-1] = "--nosmooth"

    logger.debug(f"Running the command: {' '.join(cmd)}")
    proc_status = subprocess.call(cmd)

    if proc_status != 0:
        logger.error(f"Error occured during smoothing of the raw matrix, the process will stop.")
        exit(1)

    # output files generated by params.matrix_script
    named_property = "bfactor" if property == "binding_sites" else property
    out_matrix_smoothed = str(Path(params.outdir) / "smoothed_matrices" / f"{Path(params.pdbarg).stem}_{named_property}_smoothed_matrix.txt")
    out_matrix = str(Path(params.outdir) / "matrices" / f"{Path(params.pdbarg).stem}_{named_property}_matrix.txt")

    return proc_status, out_matrix, out_matrix_smoothed        


def compute_map(params: Parameters, matrix_file: str, property: str, reslist: str=None, suffix="_smoothed_matrix.txt") -> int:
    """Compute map from a matrix file

    Args:
        params (Parameters): Object with a set of useful parameters:
            - params.map_script  # path to the script computeMaps.r
            - params.pdb_id  # PDB stem name (e.g. '1g3n')
            - params.coordstomap  # None
            - params.outdir  # path to the output directory
            - params.cellsize  # unit size of a grid cell
            - params.proj  # name of the projection type
        matrix_file (str): Path to a smoothed matrix file.
        property (str): property to map
        reslist (str): Path to the file with spherical coordinates of specific residues

    Returns:
        int: status value of the process, png output file and pdf output file 
    """
    out_pdf = str(Path(params.outdir) / "maps" / f"{params.pdb_id}_{property}_map.pdf")  # an output file generated by params.map_script
    out_png = None

    if property == "binding_sites":
        scale_opt = "--discrete"
    elif property == "circular_variance_atom":
        scale_opt = "--circular_variance"
    else:
        scale_opt = "--" + property

    cmd = ["Rscript", params.map_script, "-i", str(matrix_file), scale_opt,  "-s", str(params.cellsize), "-p", params.pdb_id, "-P", params.proj, "-o", str(params.outdir), "--suffix", suffix]
    
    if params.coordstomap:
        cmd += ["-c", params.coordstomap]
    if reslist:
        cmd += ["-l", reslist]
    if params.png:
        cmd.append("--png")
        out_png = out_pdf.replace(".pdf", ".png")
    if params.elec_max_value is not None:
        cmd += ["--elec_max_value", str(params.elec_max_value)]
    if params.bfactor_min_value is not None:
        cmd += ["--bfactor_min_value", str(params.bfactor_min_value)]
    if params.bfactor_max_value is not None:
        cmd += ["--bfactor_max_value", str(params.bfactor_max_value)]

    logger.debug(f"Running the command: {' '.join(cmd)}")
    proc_status = subprocess.call(cmd)

    if proc_status != 0:
        logger.error(f"Error occured during computing the map, the process will stop.")
        exit(1)

    return proc_status, out_png, out_pdf

def _load_coords_and_values(particles_file: Union[str, Path]):
    """
    Try to load Nx3 coordinates + a single property column from the particle list.
    This is the file returned by run_particles_mapping and then passed to compute_coords_list.
    We accept either comma-separated or whitespace-separated formats, with or without headers.
    Expected columns (best case): x,y,z,<value> (names can vary in case).
    Fallback: first 3 numeric columns are XYZ, last numeric column is the value.
    """
    particles_file = str(particles_file)

    def _try_read(delimiter, names):
        try:
            return np.genfromtxt(particles_file, delimiter=delimiter, names=names, dtype=float, autostrip=True)
        except Exception:
            return None

    # 1) Try CSV with header, then whitespace with header
    data = _try_read(",", True)
    if data is None or (hasattr(data, "shape") and data.shape == ()):
        data = _try_read(None, True)

    # 2) If no header parse worked, try without names
    if data is None or (hasattr(data, "shape") and data.shape == ()):
        data = _try_read(",", False)
        if data is None or (hasattr(data, "shape") and data.shape == ()):
            data = _try_read(None, False)


    if data is None:
        raise ValueError(f"Could not parse particle file: {particles_file}")

    # If structured array with names, look for common x/y/z names
    if data.dtype.names:
        names = [n.lower() for n in data.dtype.names]
        def _get(name_options):
            for opt in name_options:
                if opt in names:
                    return data[ data.dtype.names[names.index(opt)] ]
            return None

        xs = _get(["x", "xs", "coordx"])
        ys = _get(["y", "ys", "coordy"])
        zs = _get(["z", "zs", "coordz"])
        # value column: try common names then fallback to the last column
        vals = _get(["value", "val", "prop", "property", "electrostatics", "bfactor"])
        if vals is None:
            vals = data[data.dtype.names[-1]]


        if xs is None or ys is None or zs is None:
            # fallback: take first 3 numeric columns as XYZ
            mat = np.column_stack([data[n] for n in data.dtype.names])
            if mat.shape[1] < 4:
                raise ValueError("Expected at least 4 columns (x,y,z,value).")
            coords = mat[:, :3]
            values = mat[:, -1]
        else:
            coords = np.column_stack([xs, ys, zs])
            values = np.asarray(vals)
    else:
        # Plain numeric matrix
        mat = np.asarray(data)
        if mat.ndim == 1:
            mat = mat.reshape(1, -1)
        if mat.shape[1] < 4:
            raise ValueError(f"Expected at least 4 numeric columns in {particles_file}; got shape {mat.shape}")
        coords = mat[:, :3]
        values = mat[:, -1]

    # Basic sanity
    if coords.shape[0] != values.shape[0]:
        raise ValueError(f"Row count mismatch between coords and values in {particles_file}")

    return coords, values

def _coords_vals_from_partlist(partlist_path: Union[str, Path],
                               shell_pdb_path: Union[str, Path]):
    """Use shell PDB for XYZ and partlist 'value' (3rd column) for colors."""
    partlist_path = Path(partlist_path)
    shell_pdb_path = Path(shell_pdb_path)

    # 1) coords from shell PDB (ATOM/HETATM x,y,z; B-factor ignored here)
    xs, ys, zs = [], [], []
    with open(shell_pdb_path, "r", encoding="utf-8") as f:
        for line in f:
            if line.startswith(("ATOM  ", "HETATM")) and len(line) >= 54:
                try:
                    x = float(line[30:38]); y = float(line[38:46]); z = float(line[46:54])
                except Exception:
                    continue
                xs.append(x); ys.append(y); zs.append(z)

    if not xs:
        raise ValueError(f"No coordinates parsed from shell PDB: {shell_pdb_path}")

    coords = np.column_stack([xs, ys, zs]).astype(float)

    # 2) values from partlist third column (skip header if present)
    vals = []
    with open(partlist_path, "r", encoding="utf-8") as f:
        for line in f:
            s = line.strip()
            if not s or not any(ch.isdigit() for ch in s):
                # likely header/blank
                continue
            parts = s.replace(",", " ").split()
            if len(parts) < 3:
                continue
            try:
                v = float(parts[2])
            except Exception:
                continue
            vals.append(v)

    if not vals:
        raise ValueError(f"Could not parse values from partlist: {partlist_path}")

    vals = np.asarray(vals, float).ravel()

    # align by index length
    n = min(coords.shape[0], vals.shape[0])
    coords = coords[:n, :]
    vals = vals[:n]
    return coords, vals

def _coords_vals_from_shell_pdb(pdb_path: Union[str, Path]):
    """
    Read coordinates and per-particle values from a shell PDB.
    The value is taken from the B-factor column (columns 61-66 in PDB format).
    Returns: coords (N,3), values (N,)
    """
    xs, ys, zs, vals = [], [], [], []
    with open(pdb_path, "r", encoding="utf-8") as fh:
        for line in fh:
            if not (line.startswith("ATOM") or line.startswith("HETATM")):
                continue
            try:
                x = float(line[30:38])
                y = float(line[38:46])
                z = float(line[46:54])
                b = float(line[60:66])  # B-factor – APBS values are written here
            except Exception:
                continue
            xs.append(x); ys.append(y); zs.append(z); vals.append(b)

    if not xs:
        raise ValueError(f"No ATOM/HETATM records parsed from shell PDB: {pdb_path}")

    coords = np.column_stack([xs, ys, zs]).astype(float)
    values = np.asarray(vals, dtype=float)
    return coords, values

def _coords_from_shell_pdb(pdb_path: Union[str, Path]):
    """
    Read only XYZ coordinates from the shell PDB (ignore values).
    Returns: coords (N,3) float array, in the same order as the atoms/particles.
    """
    xs, ys, zs = [], [], []
    with open(pdb_path, "r", encoding="utf-8", errors="ignore") as fh:
        for line in fh:
            if not (line.startswith("ATOM") or line.startswith("HETATM")):
                continue
            try:
                x = float(line[30:38]); y = float(line[38:46]); z = float(line[46:54])
            except Exception:
                parts = line.split()
                if len(parts) < 9:
                    continue
                x = float(parts[6]); y = float(parts[7]); z = float(parts[8])
            xs.append(x); ys.append(y); zs.append(z)
    coords = np.column_stack([xs, ys, zs]).astype(float)
    return coords


def _values_from_partlist(partlist_path: Union[str, Path]):
    """
    Read one numeric 'value' per particle from the partlist.
    The file may be CSV or whitespace-delimited and usually has a header:
        phi  theta  value  resnb  restype  chain
    Strategy:
      1) Try structured read with names=True; if a column named 'value'
         exists (any case), use it.
      2) Else, pick the last numeric column from the structured array.
      3) Else, read as plain numeric matrix and take the last column.
    """
    p = str(partlist_path)

    # ---- Try structured with names (CSV then whitespace) ----
    for delimiter in (",", None):
        try:
            arr = np.genfromtxt(
                p,
                delimiter=delimiter,
                names=True,
                dtype=None,        # infer types; mixed dtypes OK
                autostrip=True,
                comments="#",
                encoding="utf-8",
                invalid_raise=False,
            )
        except Exception:
            arr = None

        if arr is not None and getattr(arr, "dtype", None) and arr.dtype.names:
            names = list(arr.dtype.names)
            lower = [n.lower() for n in names]

            # 1) Prefer a column literally named 'value'
            if "value" in lower:
                vals = np.asarray(arr[names[lower.index("value")]], dtype=float).ravel()
                if np.isfinite(vals).any():
                    return vals

            # 2) Otherwise, pick the last *numeric* column
            numeric_cols = []
            for name in names:
                try:
                    _ = np.asarray(arr[name], dtype=float)
                    numeric_cols.append(name)
                except Exception:
                    pass
            if numeric_cols:
                last_num = numeric_cols[-1]
                vals = np.asarray(arr[last_num], dtype=float).ravel()
                if np.isfinite(vals).any():
                    return vals
            # fall through to plain numeric

    # ---- Plain numeric matrix (CSV then whitespace) ----
    for delimiter in (",", None):
        try:
            mat = np.genfromtxt(
                p,
                delimiter=delimiter,
                dtype=float,
                autostrip=True,
                comments="#",
                invalid_raise=False,
            )
        except Exception:
            mat = None

        if mat is None:
            continue
        mat = np.asarray(mat)
        if mat.ndim == 1:
            mat = mat.reshape(1, -1)
        if mat.shape[1] >= 1:
            vals = np.asarray(mat[:, -1], dtype=float).ravel()
            if np.isfinite(vals).any():
                return vals

    raise ValueError(f"Could not parse values from partlist: {p}")

def _set_equal_3d_axes(ax, coords):
    """Make the 3D axes use the same scale so the protein doesn't look squashed."""
    mins = coords.min(axis=0)
    maxs = coords.max(axis=0)
    centers = (mins + maxs) / 2.0
    span = (maxs - mins).max()
    for setter, c in zip([ax.set_xlim, ax.set_ylim, ax.set_zlim], centers):
        r = span / 2.0
        setter([c - r, c + r])


def plot_3d_scatter(coords, values, out_path,
                    prop_name="value",
                    point_size=2.0, alpha=0.9,
                    elev=20.0, azim=35.0,
                    dpi=300,
                    elec_max_abs=None, 
                    cmap_name="viridis"):
    """
    Minimal, robust 3D scatter that works headless.
    - coords: (N,3)
    - values: (N,)
    - elec_max_abs: if not None, fix color scale to [-M, +M] (handy for electrostatics)
    """
    coords = np.asarray(coords, float)
    values = np.asarray(values, float)
    if coords.ndim != 2 or coords.shape[1] != 3:
        raise ValueError(f"coords must be (N,3), got {coords.shape}")
    if values.ndim != 1 or values.shape[0] != coords.shape[0]:
        raise ValueError(f"values must be (N,), got {values.shape}")

    fig = plt.figure(figsize=(6, 6), dpi=dpi)
    ax = fig.add_subplot(111, projection="3d")

    # choose colormap
    cmap = plt.get_cmap(cmap_name)

    # electrostatics: symmetric around 0 if a max was provided; center at 0
    if elec_max_abs is not None:
        vlim = abs(float(elec_max_abs))
        norm = mcolors.TwoSlopeNorm(vmin=-vlim, vcenter=0.0, vmax=+vlim)
        sc = ax.scatter(coords[:, 0], coords[:, 1], coords[:, 2],
                        c=values, s=point_size, alpha=alpha, cmap=cmap, norm=norm)
    else:
        sc = ax.scatter(coords[:, 0], coords[:, 1], coords[:, 2],
                        c=values, s=point_size, alpha=alpha, cmap=cmap)

    _set_equal_3d_axes(ax, coords)
    ax.set_xlabel("x")
    ax.set_ylabel("y")
    ax.set_zlabel("z")
    ax.view_init(elev=elev, azim=azim)

    cbar = fig.colorbar(sc, ax=ax, shrink=0.75, pad=0.02)
    cbar.set_label(prop_name)

    Path(Path(out_path).parent).mkdir(parents=True, exist_ok=True)
    fig.tight_layout()
    fig.savefig(out_path, bbox_inches="tight")
    plt.close(fig)



def surfmap_from_pdb(params: Parameters, with_copyright: bool=True):
    """SURFMAP pipeline function to generate a 2D map from a PDB file. 

    Args:
        params (Parameters): an instance of Parameters object (-> surfmap.lib.parameters: class Parameters)
    """
    if with_copyright:
        print(__COPYRIGHT_FULL__)
    
    # create a trash for intermediary files to remove
    junk_optional = JunkFilePath(elements=[Path(params.outdir) / "shells", Path(params.outdir) / "tmp-elec"])
    shell = None

    listtomap = ["kyte_doolittle", "stickiness", "wimley_white", "circular_variance"] if params.ppttomap == "all" else [params.ppttomap]        
    for tomap in listtomap:

        logger.info(msg=f"Surface mapping of the {tomap} property".upper())

        step_index = 1
        if shell is None:
            outdir_shell = Path(params.outdir) / "shells"
            extra_radius = params.rad
            logger.info(msg=f"Step {step_index}: computing a shell around the protein surface")
            csv_coords, shell = run_compute_shell(pdb_filename=params.pdbarg, out_dir=outdir_shell, extra_radius=extra_radius)
        else:
            logger.info(msg=f"Step {step_index}: shell already exists. Skipping this step")


        if params.ppttomap == "electrostatics":
            step_index += 1
            outdir_elec = Path(params.outdir) / "tmp-elec"
            logger.info(msg=f"Step {step_index}: computing electrostatics potential")
            shell = run_compute_electrostatics(
                pdb_filename=params.pdbarg,
                csv_filename=csv_coords,
                force_field=params.force_field,
                pqr_filename=params.pqr,
                out_dir=outdir_elec,
                salt=params.salt,          # NEW: forward ionic strength
                ph=params.ph,            # (optional) if you later add --ph to Parameters
            )


        step_index += 1
        logger.info(msg=f"Step {step_index}: computing the property values and/or assign it to the shell particles")
        property = "bfactor" if tomap == "binding_sites" else tomap
        reslist, partlist_outfile = run_particles_mapping(shell=shell, pdb=params.pdbarg, tomap=property, outdir=params.outdir, res=params.resfile)
        junk_optional.add(element=[reslist, partlist_outfile])


        # --- 3D scatter (property-aware source of values) ---
        if params.plot3d:
            logger.info("Attempting 3D plot for property '%s'…", property)
            try:
                # Decide how to get values:
                # - electrostatics: use the APBS-enriched shell PDB (B-factor holds the potential)
                # - others (WW, KD, stickiness, cv, bfactor): use the per-particle list file
                if property == "electrostatics":
                    coords3d, values = _coords_vals_from_shell_pdb(shell)
                else:
                    # NOTE: pass the shell PDB path as the second argument
                    coords3d, values = _coords_vals_from_partlist(partlist_outfile, shell)

                # Basic sanity and cleaning
                coords3d = np.asarray(coords3d, float)
                values   = np.asarray(values, float).ravel()
                n = min(coords3d.shape[0], values.shape[0])
                coords3d = coords3d[:n, :]
                values   = values[:n]

                logger.debug("Before filter: coords=%s, values=%s",
                             coords3d.shape, values.shape)
                logger.debug("values stats: finite=%d, nan=%d, min=%s, max=%s",
                            int(np.isfinite(values).sum()),
                            int(np.isnan(values).sum()),
                            (np.nanmin(values) if values.size else "NA"),
                            (np.nanmax(values) if values.size else "NA"))

                # Filter NaN/inf rows
                ok = np.isfinite(coords3d).all(axis=1) & np.isfinite(values)
                coords3d = coords3d[ok]
                values   = values[ok]
                logger.info("3D plotting: %d points after filtering", coords3d.shape[0])

                if coords3d.shape[0] == 0:
                    raise ValueError("No finite points to plot (coords/values all NaN/inf?).")

                # Build output filename
                labels = [params.pdb_id, property]
                if params.ph is not None:
                    labels.append(f"pH{params.ph:g}")
                if params.salt is not None:
                    labels.append(f"salt{params.salt:g}M")
                outfile_3d = "_".join(labels) + "_3d.png"
                out_path_3d = Path(params.outdir) / "plots_3d" / outfile_3d

                # Camera view
                elev, azim = params.plot3d_view if params.plot3d_view else (20.0, 35.0)

                # Color mapping consistent with our plan
                if property == "electrostatics":
                    cmap_name = "RdBu_r"
                    elec_max_abs = float(abs(params.elec_max_value)) if params.elec_max_value is not None else None
                else:
                    cmap_name = "viridis"
                    elec_max_abs = None

                plot_3d_scatter(
                    coords3d, values, out_path_3d,
                    prop_name=property,
                    point_size=params.plot3d_point_size,
                    alpha=params.plot3d_alpha,
                    elev=elev, azim=azim,
                    dpi=300,
                    elec_max_abs=elec_max_abs,
                    cmap_name=cmap_name,
                )
                logger.info("Saved 3D scatter: %s", out_path_3d)

            except Exception as e:
                logger.warning("3D plotting skipped due to: %s", e)
        # --- end 3D scatter ---





        step_index += 1
        logger.info(msg=f"Step {step_index}: computing the 2D {params.proj} projection coordinates of each shell particle")
        _, coordfile = compute_coords_list(params=params, coords_file=partlist_outfile, property=property)
        junk_optional.add(element=[coordfile, Path(coordfile).parent])

        
        step_index += 1
        logger.info(msg=f"Step {step_index}: dividing the 2D projection into {int(360/params.cellsize)}x{int(180/params.cellsize)} cells and smoothing the values")
        _, matrix_file, smoothed_matrix_file = compute_matrix(params=params, coords_file=coordfile, property=tomap)
        junk_optional.add(element=[matrix_file, Path(matrix_file).parent])


        step_index += 1
        logger.info(msg=f"Step {step_index}: computing the 2D map")
        _, png_filename, pdf_filename = compute_map(params=params, matrix_file=smoothed_matrix_file, property=tomap, reslist=reslist)


    # Deleting all intermediate files and directories
    if not params.keep:
        junk_optional.empty()
        
    # Creating log in output directory. Contains the parameters used to compute the maps.
    params.write_parameters(filename="parameters.log")
    print()


def surfmap_from_matrix(params: Parameters, with_copyright: bool=True):
    """SURFMAP function to generate a 2D map from a matrix file. 

    Args:
        params (Parameters): an instance of Parameters object (-> surfmap.lib.parameters: class Parameters)
    """
    if with_copyright:
        print(__COPYRIGHT_FULL__)

    if params.ppttomap == 'all':
        logger.error("Error: the property to map cannot be set to 'all' when computing a map from a matrix file.\n")
        exit()

    # create output dir and copy input matrix file in matrices/
    matrices_outdir = Path(params.outdir) / "matrices"
    matrices_outdir.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(params.mat, matrices_outdir / Path(params.mat).name)

    matf = Path(params.outdir) / "matrices" / Path(params.mat).name
    
    logger.info(msg=f"Computing the 2D map")
    _, png_filename, pdf_filename = compute_map(params=params, matrix_file=matf, property=params.ppttomap)
    
    # Creating log in output directory. Contains the parameters used to compute the maps.
    params.write_parameters(filename="parameters.log")
 

