#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import logging
from pathlib import Path
import shutil
import subprocess
from typing import Tuple, Union
import os
import numpy as np
import re
# Headless backend so this works inside Docker with no GUI
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
from matplotlib.colors import LinearSegmentedColormap, ListedColormap, TwoSlopeNorm, to_rgb, to_hex
from matplotlib.ticker import ScalarFormatter

from surfmap import PATH_MSMS, __COPYRIGHT_FULL__
from surfmap.lib.logs import get_logger
from surfmap.lib.parameters import Parameters
from surfmap.lib.utils import JunkFilePath
from surfmap.tools.SurfmapTools import run_particles_mapping
from surfmap.tools.compute_shell import run as run_compute_shell
from surfmap.tools.compute_electrostatics import run as run_compute_electrostatics


logger = get_logger(name=__name__)


def compute_coords_list(params: Parameters, coords_file: str, property: str) -> Tuple[int, str]:
    """Compute phi theta list

    Args:
        params (Parameters): Object with a set of useful parameters:
            - params.coords_script  # path to the script computeCoordsList.r
            - params.pdbarg  # pdb filename
            - params.outdir  # path to the output directory
            - params.cellsize  # unit size of a grid cell
            - params.proj  # name of the projection type
        coords_file (str): # path to filename with spherical coordinates of each residue
        property (str): property to map

    Returns:
        tuple[int, str]: return the status value of the process and the output filename
    """
    cmd = ["Rscript", params.coords_script, "-f", str(coords_file), "-s", str(params.cellsize), "-P", params.proj, "-o", params.outdir]
    
    logger.debug(f"Running the command: {' '.join(cmd)}")
    proc_status = subprocess.call(cmd)
    
    if proc_status != 0:
        logger.error(f"Error occured during the computation of spherical coordinates of particles, the process will stop.")
        exit(1)

    # output file generated by params.coords_script
    out_file = str(Path(params.outdir) / "coord_lists" / f"{Path(params.pdbarg).stem}_{property}_coord_list.txt")

    return proc_status, out_file



def compute_matrix(params: Parameters, coords_file: str, property: str, suffix="_coord_list.txt"): 
    """Compute matrix files

    Args:
        params (Parameters): Object with a set of useful parameters:
            - params.matrix_script  # path to the script computeMatrices.r
            - params.pdbarg  # pdb filename
            - params.outdir  # path to the output directory
            - params.cellsize  # unit size of a grid cell
            - params.proj  # name of the projection type
        coords_file (str): # path to filename with coords_list (output of compute_coords_list())
        property (str): property to map

    Returns:mote
        Tuple[int, str, str]: (returncode, raw_matrix_path, smoothed_matrix_path)

    Raises:
        SystemExit: If the underlying R script (`computeMatrices.R`) returns a non-zero code.

    """

    # base command
    cmd = ["Rscript", params.matrix_script, "-i", coords_file, "-s", str(params.cellsize),
           "-P", str(params.proj), "-o", str(params.outdir), "--suffix", suffix, "--discrete"]

    # adapt smoothing flags
    if property != "binding_sites":
        if not params.nosmooth:
            del cmd[-1]       # remove --discrete
        else:
            cmd[-1] = "--nosmooth"

    logger.debug("Running the command: %s", " ".join(cmd))
    status = subprocess.run(cmd)
    if status.returncode != 0:
        logger.error("computeMatrices.R failed (status %s)", status.returncode)
        exit(1)

    # output files generated by params.matrix_script
    named_property = "bfactor" if property == "binding_sites" else property
    out_matrix_smoothed = str(Path(params.outdir) / "smoothed_matrices" / f"{Path(params.pdbarg).stem}_{named_property}_smoothed_matrix.txt")
    out_matrix = str(Path(params.outdir) / "matrices" / f"{Path(params.pdbarg).stem}_{named_property}_matrix.txt")

    return status.returncode, out_matrix, out_matrix_smoothed     

from matplotlib.colors import ListedColormap

# Map R/X11 names that Matplotlib doesn't know to hex
_R_TO_HEX = {
    # blues/greens used in KD/WW/stickiness
    "cadetblue":      "#5F9EA0",
    "cadetblue3":     "#7AC5CD",
    "royalblue3":     "#3A5FCD",
    "royalblue4":     "#27408B",
    "cornflowerblue": "#6495ED",
    "skyblue1":       "#87CEFF",
    "darkgreen":      "#006400",
    "green3":         "#00CD00",
    # oranges/browns
    "orange3":        "#CD8500",
    "sienna4":        "#8A360F",
    "chocolate1":     "#FF7F24",
    "chocolate3":     "#CD661D",
    "tan3":           "#CD853F",
    "darkgoldenrod1": "#FFB90F",
    # reds/purples
    "firebrick2":     "#EE2C2C",
    "mediumorchid4":  "#7A378B",
    "palevioletred3": "#CD6889",
    # greys
    "gray30":         "#4D4D4D",
    "grey30":         "#4D4D4D",
}


def _normalize_colors_for_mpl(seq):
    """Turn mixed color names (R/X11, CSS, hex) into hex strings Matplotlib accepts."""
    norm = []
    for c in seq:
        s = (c or "").strip()
        if not s:
            continue
        if s.startswith("#"):
            norm.append(s[:7])  # strip any alpha
            continue
        lc = s.lower()
        if lc in _R_TO_HEX:               # our R→hex table
            norm.append(_R_TO_HEX[lc])
            continue
        try:                               # CSS names Matplotlib knows
            norm.append(to_hex(to_rgb(lc)))
        except Exception:
            # last resort: warn and use mid-grey so we never crash
            try:
                logger.warning("Unknown color name '%s'; substituting #808080", s)
            except Exception:
                pass
            norm.append("#808080")
    return norm

def _load_palette_from_r(outdir, prop: str):
    """
    Load an R-exported palette: <outdir>/palettes/<prop>.txt
    Each line can be a hex, an R/X11/CSS name, or an RGB triple.
    Always normalize to hex before building the colormap.
    """
    pal_path = Path(outdir) / "palettes" / f"{prop}.txt"
    if pal_path.is_file():
        try:
            raw = [ln.strip() for ln in pal_path.read_text().splitlines() if ln.strip()]
            # support "r g b" and "r,g,b" lines (0–1 or 0–255)
            colors = []
            for ln in raw:
                # try name/hex first
                try:
                    colors.append(to_hex(to_rgb(ln)))
                    continue
                except Exception:
                    pass
                # then numeric triple
                parts = [p for p in re.split(r"[,\s]+", ln) if p]
                if len(parts) == 3:
                    try:
                        vals = [float(x) for x in parts]
                        if max(vals) > 1.0:  # 0–255 → 0–1
                            vals = [v/255.0 for v in vals]
                        colors.append(to_hex(tuple(vals)))
                        continue
                    except Exception:
                        pass
                # fallback handled by normalizer below
                colors.append(ln)
            norm = _normalize_colors_for_mpl(colors)
            return ListedColormap(norm, name=f"rfile_{prop}"), str(pal_path)
        except Exception as e:
            logger.warning("Failed reading palette %s: %s", pal_path, e)
    return None, str(pal_path)

def _cmap_for_property(prop: str, outdir: Path | None = None):
    """
    Build a Matplotlib colormap matching SURFMAP's R palettes.
    1) If an exported palette file exists: use it (normalized).
    2) Otherwise: synthesize anchors that mirror computeMaps.R and normalize them.
    """
    name = (prop or "").lower()

    # 1) R-exported palette?
    if outdir is not None:
        cmap, pal_path = _load_palette_from_r(outdir, name)
        if cmap is not None:
            logger.debug("Using R palette from %s for %s", pal_path, name)
            return cmap

    # 2) Hard-coded anchors mirroring computeMaps.R defaults
    if name == "electrostatics":
        anchors = ["red", "white", "blue"]
    elif name == "stickiness":
        anchors = ["royalblue3", "white", "darkgreen"]
    elif name in ("kyte_doolittle", "wimley_white"):
        anchors = ["cadetblue", "cadetblue3", "#faf4e0", "orange3", "sienna4"]
    elif name == "circular_variance":
        anchors = ["black", "white", "blue"]
    elif name == "bfactor":
        anchors = ["chocolate3", "white", "darkblue"]
    else:
        anchors = ["#440154", "#21918c", "#fde725"]  # safe default

    cols = _normalize_colors_for_mpl(anchors)
    return LinearSegmentedColormap.from_list(f"r_{name}", cols, N=256)
# ------------------------------------------------------------------------------


def compute_map(params: Parameters, matrix_file: str, property: str, reslist: str=None, suffix="_smoothed_matrix.txt") -> int:
    """Compute map from a matrix file

    Args:
        params (Parameters): Object with a set of useful parameters:
            - params.map_script  # path to the script computeMaps.r
            - params.pdb_id  # PDB stem name (e.g. '1g3n')
            - params.coordstomap  # None
            - params.outdir  # path to the output directory
            - params.cellsize  # unit size of a grid cell
            - params.proj  # name of the projection type
        matrix_file (str): Path to a smoothed matrix file.
        property (str): property to map
        reslist (str): Path to the file with spherical coordinates of specific residues

    Returns:
        tuple[int, Optional[str], str]: (returncode, png_path_or_None, pdf_path)

    Raises:
        SystemExit: If the underlying R script (`computeMaps.R`) returns a non-zero code.

    """
    out_pdf = str(Path(params.outdir) / "maps" / f"{params.pdb_id}_{property}_map.pdf")  # an output file generated by params.map_script
    out_png = None

    if property == "binding_sites":
        scale_opt = "--discrete"
    elif property == "circular_variance_atom":
        scale_opt = "--circular_variance"
    else:
        scale_opt = "--" + property

    cmd = ["Rscript", params.map_script, "-i", str(matrix_file), scale_opt,  "-s", str(params.cellsize), "-p", params.pdb_id, "-P", params.proj, "-o", str(params.outdir), "--suffix", suffix]
    

    if params.coordstomap:
        cmd += ["-c", params.coordstomap]
    if reslist:
        cmd += ["-l", reslist]
    if params.png:
        cmd.append("--png")
        out_png = out_pdf.replace(".pdf", ".png")
    if params.elec_max_value is not None:
        cmd += ["--elec_max_value", str(params.elec_max_value)]
    if params.bfactor_min_value is not None:
        cmd += ["--bfactor_min_value", str(params.bfactor_min_value)]
    if params.bfactor_max_value is not None:
        cmd += ["--bfactor_max_value", str(params.bfactor_max_value)]

    # Build a small env so R can pick up a title suffix (pH / salt)
    env = os.environ.copy()
    title_bits = []
    if getattr(params, "ph", None) is not None:
        title_bits.append(f"pH {params.ph:g}")
    if getattr(params, "salt", None) is not None:
        title_bits.append(f"{params.salt:g} M salt")
    if title_bits:
        env["SURFMAP_TITLE_SUFFIX"] = ", ".join(title_bits)
    else:
        # ensure it’s empty if nothing to add
        env["SURFMAP_TITLE_SUFFIX"] = ""

    logger.debug(f"Running the command: {' '.join(cmd)}")
    proc_status = subprocess.call(cmd, env=env)

    if proc_status != 0:
        logger.error(f"Error occured during computing the map, the process will stop.")
        exit(1)

    return proc_status, out_png, out_pdf

def _load_coords_and_values(particles_file: Union[str, Path]):
    """
    Try to load Nx3 coordinates + a single property column from the particle list.
    This is the file returned by run_particles_mapping and then passed to compute_coords_list.
    We accept either comma-separated or whitespace-separated formats, with or without headers.
    Expected columns (best case): x,y,z,<value> (names can vary in case).
    Fallback: first 3 numeric columns are XYZ, last numeric column is the value.
    """
    particles_file = str(particles_file)

    def _try_read(delimiter, names):
        try:
            return np.genfromtxt(particles_file, delimiter=delimiter, names=names, dtype=float, autostrip=True)
        except Exception:
            return None

    # 1) Try CSV with header, then whitespace with header
    data = _try_read(",", True)
    if data is None or (hasattr(data, "shape") and data.shape == ()):
        data = _try_read(None, True)

    # 2) If no header parse worked, try without names
    if data is None or (hasattr(data, "shape") and data.shape == ()):
        data = _try_read(",", False)
        if data is None or (hasattr(data, "shape") and data.shape == ()):
            data = _try_read(None, False)


    if data is None:
        raise ValueError(f"Could not parse particle file: {particles_file}")

    # If structured array with names, look for common x/y/z names
    if data.dtype.names:
        names = [n.lower() for n in data.dtype.names]
        def _get(name_options):
            for opt in name_options:
                if opt in names:
                    return data[ data.dtype.names[names.index(opt)] ]
            return None

        xs = _get(["x", "xs", "coordx"])
        ys = _get(["y", "ys", "coordy"])
        zs = _get(["z", "zs", "coordz"])
        # value column: try common names then fallback to the last column
        vals = _get(["value", "val", "prop", "property", "electrostatics", "bfactor"])
        if vals is None:
            vals = data[data.dtype.names[-1]]


        if xs is None or ys is None or zs is None:
            # fallback: take first 3 numeric columns as XYZ
            mat = np.column_stack([data[n] for n in data.dtype.names])
            if mat.shape[1] < 4:
                raise ValueError("Expected at least 4 columns (x,y,z,value).")
            coords = mat[:, :3]
            values = mat[:, -1]
        else:
            coords = np.column_stack([xs, ys, zs])
            values = np.asarray(vals)
    else:
        # Plain numeric matrix
        mat = np.asarray(data)
        if mat.ndim == 1:
            mat = mat.reshape(1, -1)
        if mat.shape[1] < 4:
            raise ValueError(f"Expected at least 4 numeric columns in {particles_file}; got shape {mat.shape}")
        coords = mat[:, :3]
        values = mat[:, -1]

    # Basic sanity
    if coords.shape[0] != values.shape[0]:
        raise ValueError(f"Row count mismatch between coords and values in {particles_file}")

    return coords, values

def _coords_vals_from_partlist(partlist_path: Union[str, Path],
                               shell_pdb_path: Union[str, Path]):
    """Use shell PDB for XYZ and partlist 'value' (3rd column) for colors."""
    partlist_path = Path(partlist_path)
    shell_pdb_path = Path(shell_pdb_path)

    # 1) coords from shell PDB (ATOM/HETATM x,y,z; B-factor ignored here)
    xs, ys, zs = [], [], []
    with open(shell_pdb_path, "r", encoding="utf-8") as f:
        for line in f:
            if line.startswith(("ATOM  ", "HETATM")) and len(line) >= 54:
                try:
                    x = float(line[30:38]); y = float(line[38:46]); z = float(line[46:54])
                except Exception:
                    continue
                xs.append(x); ys.append(y); zs.append(z)

    if not xs:
        raise ValueError(f"No coordinates parsed from shell PDB: {shell_pdb_path}")

    coords = np.column_stack([xs, ys, zs]).astype(float)

    # 2) values from partlist third column (skip header if present)
    vals = []
    with open(partlist_path, "r", encoding="utf-8") as f:
        for line in f:
            s = line.strip()
            if not s or not any(ch.isdigit() for ch in s):
                # likely header/blank
                continue
            parts = s.replace(",", " ").split()
            if len(parts) < 3:
                continue
            try:
                v = float(parts[2])
            except Exception:
                continue
            vals.append(v)

    if not vals:
        raise ValueError(f"Could not parse values from partlist: {partlist_path}")

    vals = np.asarray(vals, float).ravel()

    # align by index length
    n = min(coords.shape[0], vals.shape[0])
    coords = coords[:n, :]
    vals = vals[:n]
    return coords, vals

def _coords_vals_from_shell_pdb(pdb_path: Union[str, Path]):
    """
    Read coordinates and per-particle values from a shell PDB.
    The value is taken from the B-factor column (columns 61-66 in PDB format).
    Returns: coords (N,3), values (N,)
    """
    xs, ys, zs, vals = [], [], [], []
    with open(pdb_path, "r", encoding="utf-8") as fh:
        for line in fh:
            if not (line.startswith("ATOM") or line.startswith("HETATM")):
                continue
            try:
                x = float(line[30:38])
                y = float(line[38:46])
                z = float(line[46:54])
                b = float(line[60:66])  # B-factor – APBS values are written here
            except Exception:
                continue
            xs.append(x); ys.append(y); zs.append(z); vals.append(b)

    if not xs:
        raise ValueError(f"No ATOM/HETATM records parsed from shell PDB: {pdb_path}")

    coords = np.column_stack([xs, ys, zs]).astype(float)
    values = np.asarray(vals, dtype=float)
    return coords, values

def _coords_from_shell_pdb(pdb_path: Union[str, Path]):
    """
    Read only XYZ coordinates from the shell PDB (ignore values).
    Returns: coords (N,3) float array, in the same order as the atoms/particles.
    """
    xs, ys, zs = [], [], []
    with open(pdb_path, "r", encoding="utf-8", errors="ignore") as fh:
        for line in fh:
            if not (line.startswith("ATOM") or line.startswith("HETATM")):
                continue
            try:
                x = float(line[30:38]); y = float(line[38:46]); z = float(line[46:54])
            except Exception:
                parts = line.split()
                if len(parts) < 9:
                    continue
                x = float(parts[6]); y = float(parts[7]); z = float(parts[8])
            xs.append(x); ys.append(y); zs.append(z)
    coords = np.column_stack([xs, ys, zs]).astype(float)
    return coords


def _values_from_partlist(partlist_path: Union[str, Path]):
    """
    Read one numeric 'value' per particle from the partlist.
    The file may be CSV or whitespace-delimited and usually has a header:
        phi  theta  value  resnb  restype  chain
    Strategy:
      1) Try structured read with names=True; if a column named 'value'
         exists (any case), use it.
      2) Else, pick the last numeric column from the structured array.
      3) Else, read as plain numeric matrix and take the last column.
    """
    p = str(partlist_path)

    # ---- Try structured with names (CSV then whitespace) ----
    for delimiter in (",", None):
        try:
            arr = np.genfromtxt(
                p,
                delimiter=delimiter,
                names=True,
                dtype=None,        # infer types; mixed dtypes OK
                autostrip=True,
                comments="#",
                encoding="utf-8",
                invalid_raise=False,
            )
        except Exception:
            arr = None

        if arr is not None and getattr(arr, "dtype", None) and arr.dtype.names:
            names = list(arr.dtype.names)
            lower = [n.lower() for n in names]

            # 1) Prefer a column literally named 'value'
            if "value" in lower:
                vals = np.asarray(arr[names[lower.index("value")]], dtype=float).ravel()
                if np.isfinite(vals).any():
                    return vals

            # 2) Otherwise, pick the last *numeric* column
            numeric_cols = []
            for name in names:
                try:
                    _ = np.asarray(arr[name], dtype=float)
                    numeric_cols.append(name)
                except Exception:
                    pass
            if numeric_cols:
                last_num = numeric_cols[-1]
                vals = np.asarray(arr[last_num], dtype=float).ravel()
                if np.isfinite(vals).any():
                    return vals
            # fall through to plain numeric

    # ---- Plain numeric matrix (CSV then whitespace) ----
    for delimiter in (",", None):
        try:
            mat = np.genfromtxt(
                p,
                delimiter=delimiter,
                dtype=float,
                autostrip=True,
                comments="#",
                invalid_raise=False,
            )
        except Exception:
            mat = None

        if mat is None:
            continue
        mat = np.asarray(mat)
        if mat.ndim == 1:
            mat = mat.reshape(1, -1)
        if mat.shape[1] >= 1:
            vals = np.asarray(mat[:, -1], dtype=float).ravel()
            if np.isfinite(vals).any():
                return vals

    raise ValueError(f"Could not parse values from partlist: {p}")

def _set_equal_3d_axes(ax, coords):
    """Make the 3D axes use the same scale so the protein doesn't look squashed."""
    mins = coords.min(axis=0)
    maxs = coords.max(axis=0)
    centers = (mins + maxs) / 2.0
    span = (maxs - mins).max()
    for setter, c in zip([ax.set_xlim, ax.set_ylim, ax.set_zlim], centers):
        r = span / 2.0
        setter([c - r, c + r])



def _colorbar_label_for_property(prop: str) -> str:
    """Return a publication-style colorbar label for a given property."""
    prop = (prop or "").lower()
    if prop == "electrostatics":
        return "Electrostatic Potential [kT/e]"
    if prop == "kyte_doolittle":
        return "Kyte-Doolittle Hydrophobicity [-]"
    if prop == "wimley_white":
        return "Wimley-White Hydrophobicity [kcal/mol]"
    if prop == "stickiness":
        return "Stickiness [–]"
    if prop == "circular_variance":
        return "Circular Variance [–]"
    if prop == "bfactor":
        return "B-factor [Å²]"
    # fallback
    return f"{prop} [–]" if prop else "Value [–]"

def export_points_csv(coords, values, out_path_csv):
    """
    Write 3D points to CSV with header: x,y,z,value.
    Filters out non-finite rows and aligns coords/values by the shortest length.
    """
    coords = np.asarray(coords, float)
    values = np.asarray(values, float).ravel()

    # Ensure matching length
    n = min(coords.shape[0], values.shape[0])
    coords = coords[:n, :]
    values = values[:n]

    # Keep only finite rows
    ok = np.isfinite(coords).all(axis=1) & np.isfinite(values)
    coords = coords[ok]
    values = values[ok]

    out_path_csv = Path(out_path_csv)
    out_path_csv.parent.mkdir(parents=True, exist_ok=True)

    with open(out_path_csv, "w", encoding="utf-8", newline="") as f:
        f.write("x,y,z,value\n")
        for (x, y, z), v in zip(coords, values):
            f.write(f"{x},{y},{z},{v}\n")

    return str(out_path_csv)

def plot_3d_scatter(
    coords, values, out_path,
    prop_name="value",
    point_size=2.0, alpha=0.9,
    elev=20.0, azim=35.0,
    dpi=300,
    elec_max_abs=None,
    cmap_name="viridis",
    cmap_obj=None,
    title=None ):

    coords = np.asarray(coords, float)
    values = np.asarray(values, float)
    if coords.ndim != 2 or coords.shape[1] != 3:
        raise ValueError(f"coords must be (N,3), got {coords.shape}")
    if values.ndim != 1 or values.shape[0] != coords.shape[0]:
        raise ValueError(f"values must be (N,), got {values.shape}")

    fig = plt.figure(figsize=(6, 6), dpi=dpi)
    ax = fig.add_subplot(111, projection="3d")

    # prefer explicit object over name
    cmap = cmap_obj if cmap_obj is not None else plt.get_cmap(cmap_name)

    if elec_max_abs is not None:
        v = abs(float(elec_max_abs))
        norm = TwoSlopeNorm(vmin=-v, vcenter=0.0, vmax=+v)
        sc = ax.scatter(coords[:, 0], coords[:, 1], coords[:, 2],
                        c=values, s=point_size, alpha=alpha, cmap=cmap, norm=norm)
    else:
        sc = ax.scatter(coords[:, 0], coords[:, 1], coords[:, 2],
                        c=values, s=point_size, alpha=alpha, cmap=cmap)

    _set_equal_3d_axes(ax, coords)
    ax.set_xlabel("x"); ax.set_ylabel("y"); ax.set_zlabel("z")
    ax.view_init(elev=elev, azim=azim)

    # --- colorbar ---
    cbar = fig.colorbar(sc, ax=ax, shrink=0.75, pad=0.02)
    cbar.set_label(prop_name)
    # Use raw numeric ticks (no fixed rounding)
    sf = ScalarFormatter(useOffset=False, useMathText=False)
    sf.set_powerlimits((-10, 10))  # avoid scientific notation for typical ranges
    cbar.ax.yaxis.set_major_formatter(sf)
    cbar.update_ticks()

    # --- layout & title ---
    if title:
        # reserve a bit of top margin so the suptitle isn't clipped
        fig.tight_layout(rect=[0, 0, 1, 0.95])
        fig.suptitle(title)
    else:
        fig.tight_layout()

    # --- save ---
    Path(Path(out_path).parent).mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, bbox_inches="tight")
    plt.close(fig)


def _pretty_prop_name(prop: str) -> str:
    return {
        "electrostatics":    "Electrostatic potential",
        "kyte_doolittle":    "Hydrophobicity (Kyte–Doolittle)",
        "wimley_white":      "Hydrophobicity (Wimley–White)",
        "stickiness":        "Stickiness",
        "circular_variance": "Circular variance",
        "bfactor":           "B-factor",
    }.get(prop, prop)

def surfmap_from_pdb(params: Parameters, with_copyright: bool = True):
    """SURFMAP pipeline function to generate a 2D map from a PDB file."""
    if with_copyright:
        print(__COPYRIGHT_FULL__)

    # where we’ll clean up intermediates unless --keep
    junk_optional = JunkFilePath(elements=[Path(params.outdir) / "shells",
                                           Path(params.outdir) / "tmp-elec"])
    shell = None

    # which properties to map
    listtomap = (["kyte_doolittle", "stickiness", "wimley_white", "circular_variance"]
                 if params.ppttomap == "all" else [params.ppttomap])

    for tomap in listtomap:
        logger.info(msg=f"Surface mapping of the {tomap} property".upper())

        # --- Step 1: shell ---------------------------------------------------
        step_index = 1
        if shell is None:
            outdir_shell = Path(params.outdir) / "shells"
            extra_radius = params.rad
            logger.info(msg=f"Step {step_index}: computing a shell around the protein surface")
            csv_coords, shell = run_compute_shell(
                pdb_filename=params.pdbarg,
                out_dir=outdir_shell,
                extra_radius=extra_radius
            )
        else:
            logger.info(msg=f"Step {step_index}: shell already exists. Skipping this step")

        # --- Step 2: electrostatics (only when requested) --------------------
        if params.ppttomap == "electrostatics":
            step_index += 1
            outdir_elec = Path(params.outdir) / "tmp-elec"
            logger.info(msg=f"Step {step_index}: computing electrostatics potential")
            shell = run_compute_electrostatics(
                pdb_filename=params.pdbarg,
                csv_filename=csv_coords,
                force_field=params.force_field,
                pqr_filename=params.pqr,
                out_dir=outdir_elec,
                salt=params.salt,
                ph=params.ph,
            )

        # --- Step 3: assign property values to shell particles ---------------
        step_index += 1
        logger.info(msg=f"Step {step_index}: computing the property values and/or assign it to the shell particles")
        property = "bfactor" if tomap == "binding_sites" else tomap
        reslist, partlist_outfile = run_particles_mapping(
            shell=shell, pdb=params.pdbarg, tomap=property, outdir=params.outdir, res=params.resfile
        )
        junk_optional.add(element=[reslist, partlist_outfile])

        # --- Optional: 3D scatter + CSV -------------------------------------
        # We export the CSV if --csv3d is set, and we plot if --plot3d is set.
        if params.plot3d or params.csv3d:
            logger.info("Attempting 3D output for property '%s'…", property)
            try:
                # Decide how to get values:
                # - electrostatics: APBS-enriched shell PDB (B-factor holds the potential)
                # - others: values from partlist + coords from shell
                if property == "electrostatics":
                    coords3d, values = _coords_vals_from_shell_pdb(shell)
                else:
                    coords3d, values = _coords_vals_from_partlist(partlist_outfile, shell)

                # Basic sanity and cleaning
                coords3d = np.asarray(coords3d, float)
                values = np.asarray(values, float).ravel()

                n = min(coords3d.shape[0], values.shape[0])
                coords3d = coords3d[:n, :]
                values = values[:n]

                logger.debug("Before filter: coords=%s, values=%s", coords3d.shape, values.shape)
                logger.debug(
                    "values stats: finite=%d, nan=%d, min=%s, max=%s",
                    int(np.isfinite(values).sum()),
                    int(np.isnan(values).sum()),
                    (np.nanmin(values) if values.size else "NA"),
                    (np.nanmax(values) if values.size else "NA"),
                )

                # Filter out rows with non-finite numbers
                ok = np.isfinite(coords3d).all(axis=1) & np.isfinite(values)
                coords3d = coords3d[ok]
                values = values[ok]
                logger.info("3D: %d points after filtering", coords3d.shape[0])

                if coords3d.shape[0] == 0:
                    raise ValueError("No finite points to output (coords/values all NaN/inf?).")

                # Build common base filename (used for CSV and optionally plot)
                labels = [params.pdb_id, property]
                if params.ph is not None:
                    labels.append(f"pH{params.ph:g}")
                if params.salt is not None:
                    labels.append(f"salt{params.salt:g}M")
                base = "_".join(labels)

                out_path_csv = Path(params.outdir) / "points_3d" / (base + "_3d_points.csv")
                out_path_3d  = Path(params.outdir) / "plots_3d"  / (base + "_3d.png")

                # --- write CSV if requested ---
                if params.csv3d:
                    csv_written = export_points_csv(coords3d, values, out_path_csv)
                    logger.info("Saved 3D points CSV: %s", csv_written)

                # --- write plot if requested ---
                if params.plot3d:
                    # Camera view
                    elev, azim = params.plot3d_view if params.plot3d_view else (20.0, 35.0)

                    # Colormap (prefer R-exported palette; otherwise fallback that matches R)
                    cmap_obj = _cmap_for_property(property, outdir=Path(params.outdir))

                    # Symmetric bounds for electrostatics if a max was provided
                    elec_max_abs = (
                        float(abs(params.elec_max_value))
                        if (property == "electrostatics" and params.elec_max_value is not None)
                        else None
                    )

                    prop_pretty = _pretty_prop_name(property)
                    line1 = f"{prop_pretty} — {params.pdb_id}"
                    line2_parts = []
                    if params.ph is not None:
                        line2_parts.append(f"pH {params.ph:g}")
                    if params.salt is not None:
                        line2_parts.append(f"{params.salt:g} M salt")
                    title3d = line1 if not line2_parts else f"{line1}\n{'  |  '.join(line2_parts)}"
                    cbar_label = _colorbar_label_for_property(property)

                    plot_3d_scatter(
                        coords3d, values, out_path_3d,
                        prop_name=cbar_label,          # label with unit
                        point_size=params.plot3d_point_size,
                        alpha=params.plot3d_alpha,
                        elev=elev, azim=azim,
                        dpi=300,
                        elec_max_abs=elec_max_abs,
                        cmap_name=None,
                        cmap_obj=cmap_obj,
                        title=title3d,
                    )
                    logger.info("Saved 3D scatter: %s", out_path_3d)

            except Exception as e:
                logger.warning("3D output skipped due to: %s", e)
        # --- end 3D scatter + CSV -------------------------------------------



        # --- Step 4: project to 2D (coords list) -----------------------------
        step_index += 1
        logger.info(msg=f"Step {step_index}: computing the 2D {params.proj} projection coordinates of each shell particle")
        _, coordfile = compute_coords_list(params=params, coords_file=partlist_outfile, property=property)
        junk_optional.add(element=[coordfile, Path(coordfile).parent])

        # --- Step 5: grid + smoothing ----------------------------------------
        step_index += 1
        logger.info(msg=f"Step {step_index}: dividing the 2D projection into {int(360/params.cellsize)}x{int(180/params.cellsize)} cells and smoothing the values")
        _, matrix_file, smoothed_matrix_file = compute_matrix(params=params, coords_file=coordfile, property=tomap)
        junk_optional.add(element=[matrix_file, Path(matrix_file).parent])

        # --- Step 6: final 2D map --------------------------------------------
        step_index += 1
        logger.info(msg=f"Step {step_index}: computing the 2D map")
        _, png_filename, pdf_filename = compute_map(
            params=params, matrix_file=smoothed_matrix_file, property=tomap, reslist=reslist
        )

    # cleanup
    if not params.keep:
        junk_optional.empty()

    params.write_parameters(filename="parameters.log")
    print()



def surfmap_from_matrix(params: Parameters, with_copyright: bool=True):
    """SURFMAP function to generate a 2D map from a matrix file. 

    Args:
        params (Parameters): an instance of Parameters object (-> surfmap.lib.parameters: class Parameters)
    """
    if with_copyright:
        print(__COPYRIGHT_FULL__)

    if params.ppttomap == 'all':
        logger.error("Error: the property to map cannot be set to 'all' when computing a map from a matrix file.\n")
        exit()

    # create output dir and copy input matrix file in matrices/
    matrices_outdir = Path(params.outdir) / "matrices"
    matrices_outdir.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(params.mat, matrices_outdir / Path(params.mat).name)

    matf = Path(params.outdir) / "matrices" / Path(params.mat).name
    
    logger.info(msg=f"Computing the 2D map")
    _, png_filename, pdf_filename = compute_map(params=params, matrix_file=matf, property=params.ppttomap)
    
    # Creating log in output directory. Contains the parameters used to compute the maps.
    params.write_parameters(filename="parameters.log")
 

